steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - asia-northeast3-docker.pkg.dev/hwp2pdf-499911/hwp2pdf/hwp2pdf-converter:staging-private-candidate
      - .
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - asia-northeast3-docker.pkg.dev/hwp2pdf-499911/hwp2pdf/hwp2pdf-converter:staging-private-candidate
